# This is a basic workflow to help you get started with Actions

name: 03-Steps

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Display the path
        run: echo $PATH
        shell: bash
      - name: Display the path
        continue-on-error: true
        run: echo %PATH%
        shell: cmd
      - name: Display the path
        continue-on-error: true
        run: echo ${env:PATH}
        shell: pwsh
      - name: Display the path
        continue-on-error: true
        run: echo ${env:PATH}
        shell: powershell
      - name: Display the path
        continue-on-error: true
        run: |
          import os
          print(os.environ['PATH'])
        shell: python
      - name: Display the environment variables and their values
        continue-on-error: true
        run: |
          print %ENV
        shell: perl {0}    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Reference a specific commit
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
      # Reference the major version of a release
      - uses: actions/checkout@v3
      # Reference a specific version
      - uses: actions/checkout@v3.2.0
      # Reference a branch
      - uses: actions/checkout@main

